Changes
lib/Alien/Base/ModuleBuild.pm
lib/Alien/Base/ModuleBuild/API.pod
t/builder.t

This saves installing unnecessary prereqs if we know they are not needed.
Example savings: Strawberry Perl comes with libffi now, so you don't need Alien::MSYS to install Alien::FFI.

Only inject alien_bin_requires and Alien::MSYS prereqs if a source code build is necessary.

---

lib/Alien/Base/ModuleBuild.pm
lib/Alien/Base/ModuleBuild/Repository.pm
lib/Alien/Base/ModuleBuild/Repository/HTTP.pm
t/http_uri.t

This adds support for HTTPS repositories since both `HTTP::Tiny` and
`LWP::UserAgent` can support the HTTPS protocol. This change adds to the
`Alien::Base::ModuleBuild::Repository::HTTP` repository class.

add support for HTTPS repositories

---

lib/Alien/Base.pm
lib/Alien/Base/ModuleBuild/API.pod

Now that `FFI::Platypus` is on CPAN I'd like to prefer it in the Alien::Base documentation over `FFI::Raw`.
Full disclosure: I am the author of `FFI::Platypus` (but patches welcome!)
Platypus is newer than Raw, but it has some significant performance advantages and a number of features that Raw lacks.

prefer FFI::Platypus to FFI::Raw in documentation

---

lib/Alien/Base/ModuleBuild.pm
lib/Alien/Base/ModuleBuild/API.pod
t/builder.t

This patch allows for use of the multiple argument form of `system`.  Sometimes this is desirable:
- the multiple argument form doesn't usually invoke the shell
- quoting is not portable, so the multiple argument version is frequently the more portable way to introduce space into an argument
I'd be using this in `Alien::FFI` which has some pretty hairy stuff for Windows and especially for Visual C++ support.

allow for multiple argument do_system

---

lib/Alien/Base/ModuleBuild.pm

Debugging a issue with `Alien::FFI` on MSWin32 and it was useful to be able to see the commands as they would actually be executed, without actually executing, so I added an ACTION_alien_dry_run.
Its not quite as clever as I would like it to be (ie, would be nice to probe the repositories and tell me exactly which one(s) it would download), but I think this is a good start.

./Build alien_dry_run

---

Changes
lib/Alien/Base/ModuleBuild.pm

These diagnostics would have saved me some time tonight.
The diagnostic about requiring at least one repository is fatal either way, it is just that it catches it earlier with this patch.  IF we want to support builds that lack any repositories then we need to restructure the code so that we can do that.  I don't see that it is a useful thing to do.
The other diagnostic just gives a hint as to what you need to do.  Even though I kind of know what needed to be done, I couldn't remember what the method I had to implement in order to get it to work.  If someone else were trying to use it they'd have even more trouble since they hadn't implemented it :)

New diagnostics

---

Build.PL
lib/Alien/Base.pm

This improves the `dynamic_libs` method to be more reliable, especially under `blib` conditions for cpantesters.  Just to give you an idea I added a similar feature as a monkey patch to `Acme::Ford::Prefect::FFI` and just take a look at the differences in the testing matrix before:
http://matrix.cpantesters.org/?dist=Acme-Ford-Prefect-FFI%200.08
after:
http://matrix.cpantesters.org/?dist=Acme-Ford-Prefect-FFI%200.09
This patch also has the nice in that it moves the "what is a dynamic library" logic into `FFI::CheckLib`, which is much more reliable in this regard (it knows about .bundle files for example which can be used on OS X in addition to .dylib) than either the old implementation of `dynamic_libs` or `Config` (which was at one point a suggestion).

Better support for ffi via dynamic_libs

---

lib/Alien/Base.pm
t/inline.t
t/inline_cpp.t

This would probably have fixed this test failure:
http://ppm4.activestate.com/x86_64-linux/5.20/2000/P/PL/PLICEASE/Alien-Base-0.010.d/log20150217T080630.txt
Looks like it is trying to use a blib install gone bad.  Isolating the problem with Acme::Alien::DontPanic would ultimately be good, but I don't want that to block a working Alien::Base install.

skip inline* tests when Acme::Alien::DontPanic has an obviously bad dist_dir

---

lib/Alien/Base.pm

After releasing 0.011 I noticed almost immediately that installs with bin_dir and install_type=system were failing.
This will fix that.  I am merging to get this fix out right away because I consider it critical, making it a PR for visibility.

bin_dir should only consult dist_dir if it is a share install

---

.travis.yml
lib/Alien/Base.pm
lib/Alien/Base/ModuleBuild.pm

This updates the `-L` and `-I` flags to the correct paths when the share dir gets relocated, something that is supported by recent Perls.  My first attempt at this (see branch "movable" if interested) was to provide a `%s` placeholder in the ConfigData and expand it in `Alien::Base`, but this seemed unnecessarily complicated (Also the implementation is incomplete).
It should also handle a weird corner case when Perl is configured to install modules to a different directory form where modules get used.  This is the default for AFS.  It is also the case at `$work` where the SAs have a mildly idiotic install procedure for perl modules.
This kind of thing is tricky to test from `Test::More`, so I opted to add a test in the `.travis.yml` by installing with `cpanm` and the `-l` flag.
I noticed …

Don't Panic when install gets relocated

---

Build.PL
lib/Alien/Base.pm
lib/Alien/Base/PkgConfig.pm

This will prefer PkgConfig.pm on 64 bit Solaris Perls.
The problem with 64 bit Solaris (I believe AIX and HP-UX are similar) is that it is a dual 32/64 bit system where most of the tools are actually 32 bit and the default compiler output is 32 bit.  pkg-config does not come with Solaris by default, but if you do build it from source it will point to 32 bit libs and header files. `PkgConfig.pm` (as of version 0.08826) looks in the correct `lib/pkgconfig` directories if it is invoked by a 64 bit Perl.  This is a reasonable default.
If the end user needs explicit control over which directories to search for `.pc` files he/she can still set `PKG_CONFIG_PATH` or `PKG_CONFIG_LIBPATH`.
This does not resolve the problem of building libs from source, which is a thornier issue.

prefer PkgConfig.pm over pkg-config on 64 bit Solaris

---

lib/Alien/Base/ModuleBuild.pm
lib/Alien/Base/ModuleBuild/API.pod

This should resolve the issue raised in this comment:
https://github.com/Perl5-Alien/Alien-Base/issues/94#issuecomment-76234928
Problem is that ActiveState Perl when constructing ppm files uses just the files in `blib`.  They do not, in fact, run `./Build install` at all.  Happily a PPM build can be detected through an environment variable.
Instead of installing to the final location during the `./Build install` we install to the staged share directory during the `./Build` step for ActiveState installs ONLY, or if the AB subclass requests it.  I plan on using this feature for `Alien::FFI` even for non AS installs.
In addition, this PR would resolve #94 completely if made the default, which I think we should consider, but is not included in this patch.  We can discuss making this a default …

stage install to blib when building PPM files for ActiveState

---

lib/Alien/Base/ModuleBuild.pm
t/builder.t

This addresses the dynamic library relocation issue mentioned by @jberger by correcting the .dylib file's id field.  I tested this with `Alien::Editline` and `Term::EditLine` by setting `alien_isoloate_dynamic` to `0`, and `alien_stage_install` to `1`.  This allowed me to reproduce the problem, and correct it.

OS X dylib relocation

---

lib/Alien/Base/ModuleBuild/File.pm
t/http.t

Real-world fetching of an absolute HTTP URI (as you find with zlib for example) leads to an error because the expander is passed the URI instead of the bare name of the downloaded file:
* the patch to t/http.t shows this problem
* the patch to  lib/Alien/Base/ModuleBuild/File.pm solves the problem
The third commit is an optional cosmetic change that tidies get() up a bit. In particular, the return value at the end has been changed to make it consistent with the return at line 39.
Thanks a lot for Alien::Base!!!

Patch download and extraction of absolute HTTP URIs

---

lib/Alien/Base/ModuleBuild.pm
lib/Alien/Base/ModuleBuild/API.pod

As alluded to in #94 and #114 I would like to make `alien_stage_install=1` be the default behavior.  The main motivation for this is to make cpan testers work the same way as a regular install.  This would, in my opinion, fix #94.  The main reason not to do this up until now is that relocation weren't supported, especially on OS X.  With the inclusion of #115 this does not appear to be a problem anymore.
Although I do not think this change should have an effect on most `Alien::Base` based distributions, this is a change in behavior, and I propose this conservative approach to deployment:
* 0.016 goes out as planned with what is in master right now (d013789f1d79d72319c634d322efedc5d3ab8902 more or less)
* once that has been released to CPAN, I will post to blogs.perl.org announcing the …

make a staged install the default

---

lib/Alien/Base/ModuleBuild.pm

This is an alternate solution for #120, which I now mildly prefer.
For a blib install (either cpan testers or alien_stage_install) it does the actual `ACTION_alien_install` inside the `process_share_dir_files`, which ensures that the config data is updated BEFORE `ACTION_config_data` is called, thus negating the need to force the update of ConfigData.pm.
This fixes a bug that has existed for a long time but is exposed in a critical manner on CPAN as of 0.016, so a fast resolution would be highly desirable.

all ACTION_alien_install from process_share_dir_files when installing to blib

---

lib/Alien/Base/ModuleBuild.pm
lib/Alien/Base/ModuleBuild/API.pod
t/builder.t

This would allow the same lib directory to be shared in a non-homogeneous network environment (see #118 for related discussion).  I have worked in these environments in the past, it is particularly useful with AFS.
Looking closely at the `Module::Build` and `ExtUtils::Install` source, the only way to force an install into the arch directory is if the blib/arch directory is not empty, so I propose putting a .txt file in there with the name of the module with a comment explaining its existence.
@jberger mentioned Mach as being an exception where you might want to install into a non-arch specific directory in a non-homogeneous environment.  The only example where mach is typically used with Perl that I could think of is OS X where the arch is the same for intel, ppc, 32 and 64 bit platforms, …

Install into architecture specific directory by default

---

t/builder.t

There are a number of failures on cygwin reported by cpan testers.
A //tmp was being used on cygwin which means the remote host tmp, instead of /tmp as it does on Linux

Fix for cygwin

---

Build.PL
lib/Alien/Base.pm

I propose that we advertise the IRC channel #alien for all things `Alien` and `Alien::Base`.  We discussed having a place on IRC back when we created the mailing list, but since I wasn't on IRC and nobody else seemed keen, we didn't do it at that time.  At YAPC::NA @felliott pointed out to me that there was a (very quiet) #alien and I've come around to the idea that it is a good way to interact for quick questions where opening an issue or PR is not appropriate.  Plus with the meta change metacpan users get a big red button that they can click on for support.  I believe @jberger and @zmughal are on this channel and I am set up now to be there at least part time as well, though I am an IRC noob.
Since there does seem to some overlap @felliott suggested using this for FFI / Platypus as …

Add IRC info to meta and documentation

---

lib/Alien/Base.pm
lib/Alien/Base/ModuleBuild.pm
lib/Alien/Base/ModuleBuild/API.pod
t/interpolate.t

Here is an alternative to #129 based on suggestions made by @shadowcat-mst
Helpers can be strings of Perl code (in `Build.PL`) or code references (from `Alien::foo`).  To define helpers from an Alien module (does not need to be based on AB), simply return a hashref of helpers from a sub named `alien_helper`.

interpolate helpers

---

lib/Alien/Base.pm
lib/Alien/Base/ModuleBuild.pm
t/builder.t

`alien_provides_cflags` and `alien_provides_libs` aren't honored currently when the library is provided by the system (either with or without pkg-config).  This PR will fix that.  I have a test for the builder itself.  I have tested this with 
https://github.com/plicease/Alien-Libbz2
To ensure that it also works once installed.  I will add that to the travis for AB so that we can catch any regressions there.

honor alien_provides_* on system install

---

lib/Alien/Base/FAQ.pod
lib/Alien/Base/ModuleBuild.pm
lib/Alien/Base/ModuleBuild/API.pod
t/interpolate.t

The idea is to avoid the user having to know that `Alien:Base::PkgConfig->pkg_config_command` is the magic incantation for determining the correct `pkg-config` (which could be either `pkg-config` or it could be `PkgConfig.pm`).  Example:
https://github.com/plicease/alien-sodium/commit/ab73d208fcd1343122aba11d699865dfb91fb116

provide a %{pkg_cofig} by default

---

.travis-test-upgrade.sh
.travis.yml
lib/Alien/Base/ModuleBuild.pm
lib/Alien/Base/ModuleBuild/API.pod

It is useful for system packagers to force a system install so they don't waste their time trying to build from source when creating .deb or .rpm files.
It may also be useful for the paranoid if they don't want to be downloading random packagers from the internet (some people differentiate between "cpan" and the "internet").
I didn't want to overload ALIEN_FORCE since ALIEN_FORCE=0 has never meant  system only.  Also ALIEN_INSTALL_TYPE takes priority since it is newer.
If this interface is acceptable we can phase out any reference to ALIEN_FORCE in the documentation and recommend ALIEN_INSTALL_TYPE.

add ALIEN_INSTALL_TYPE to force system install

---

lib/Alien/Base/ModuleBuild.pm

Currently when you run `Build test` or `Build install` on a staged install (where the `make install` gets run during the `Build` step into the blib directory) it runs `make install` first (or whatever the install command is).  This is really annoying as it spams the terminal with the redundant install.
This makes sure the `make install` only happens once, as it should.

only do the alien install once

---

lib/Alien/Base/FAQ.pod

I would like to recommend `Test::Alien` instead of `Test::CChecker`.  I am the author of both, so if you have any questions about them please let me know.
I am also adding `Test::Alien` to the travis build as I am planning on adding `Test::Alien` tests to the Acme modules to see if I can flush out any issues with `Test::Alien`.

suggest new Test::Alien instead of Test::CChecker

---

lib/Alien/Base/ModuleBuild.pm

The logic to extract archives (i.e. tar files) was hardcoded inside
the 'ACTION_alien_code' method to use Archive::Extract. That didn't
allowed one to use some custom mechanism.
This patch moves that logic into the new method
'alien_extract_archive' which can be overrided in subclasses.

move archive extraction logic into overridable method

---

.gitignore
lib/Alien/Base.pm

This will fix errors like this:
http://www.cpantesters.org/cpan/report/8fd11466-6bf6-1014-a76b-fd2118e9470d

use / instead of \ on relocated paths on windows

---

lib/Alien/Base.pm
lib/Alien/Base/PkgConfig.pm

For packages providing multiple libraries and so, multiple .pc files,
it is possible for some keys to not be defined in all of them.
Specifically, OpenSSL doesn't defined "Libs" in all the .pc files.
This change just silences a warning that was generated at runtime when
looking for a keyword not available in some .pc file.

no warnings for dist with several .pc files

---

lib/Alien/Base/ModuleBuild.pm

If the command fails, but there is some output we get a false positive.  This problem was discovered when using perl Build.PL verbose=1 (and demonstrated with Alien::LibYAML).  While this exact problem
will hopefully be fixed with PR #147, there are other strangeisms that could infect the captured output with bogus data.

Test success on version probe

---

lib/Alien/Base/ModuleBuild.pm
lib/Alien/Base/ModuleBuild/API.pod
t/builder.t
t/interpolate.t

Add a property for use in overriding environment variables used by `alien_do_system`.  For the rationale, see 
https://github.com/salva/p5-Alien-OpenSSL/issues/1
and cpantesters failure:
http://cpantesters.org/cpan/report/42a41d60-6fdd-1014-8c40-57d8de5a8c74

add alien_env property

---

Changes
lib/Alien/Base/FAQ.pod
lib/Alien/Base/ModuleBuild.pm
lib/Alien/Base/ModuleBuild/API.pod
t/builder.t

Two minor cleanup items.
Officially deprecate `%p`.  Basically it isn't portable.  I have explained in other places why this really shouldn't ever be used, if anyone wants details let me know.
Use `Alien::CMake` 0.07 as a minimum when specified as a alien_bin_requires.  This version provides enough `Alien::Base` compatibility that it can be used as-is without any special case as an alien_bin_requires.

%p and cmake

---

lib/Alien/Base/ModuleBuild/Repository.pm
t/repository.t

This should address #161
Briefly, the issue is that:
- When not using `exact_filename` we get the correct base URL because we look at the HTTP response on the index and will get the trailing slash if it is needed.
- When using `exact_filename` we should append a trailing slash if it is not there already.  I can't think of a time when you wouldn't want to do this.

add trailing / when using exact filename

---

t/builder.t

I just noticed, this test fails if ALIEN_INSTALL_TYPE is set to system.
```
t/builder.t ......................... 1/? Requested system install, but system package not detected. at /home/ollisg/dev/Alien-Base/lib/Alien/Base/ModuleBuild.pm line 371.
t/builder.t ......................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```

unset ALIEN_INSTALL_TYPE in test

---

lib/Alien/Base/PkgConfig.pm
t/pkgconfig.t
t/pkgconfig/test.pc

It got confused by lines contaninig both colons and equal signs. I've also updated the tests.

fix A::B::PkgConfig::read

---

lib/Alien/Base/ModuleBuild.pm

As @wbraswell reminded me, undef entries can get put in `@PATH` if there is a trailing ; in windows, or trailing : in UNIX. This was causing an annoying but harmless diagnostic in some cpantesters results.  I was able to reproduce the diagnostic and confirmed that this removed it.

remove undef entries in Env @PATH

---

lib/Alien/Base.pm
t/alien_base.t

If I had a nickle for every time that I tried to call `$alien->version` then I would be able to afford to go to the movies in a theatre with nice large reserved seats.  This is my proposal to add a version method to get at the configuration data that is determined at install time.  It has the nice bonus that it shaves off the new line that may be there, because for system installs it just puts the output from `pkg-config --version` unless you have overridden the system detection logic.

add a version method

---

lib/Alien/Base/ModuleBuild.pm
t/builder.t

HTTP::Tiny can do SSL, but only if the appropriate modules are loaded.
The lack of this is largely responsible for most of the current failures
of Acme-Alien-DontPanic:
http://matrix.cpantesters.org/?dist=Acme-Alien-DontPanic%200.030
But all is good if we can inject the required ssl at the AB::MB level.

Add required SSL modules for https
